export const ANIMATE_TYPES = {
  NUMBER_GROWING: 'NUMBER_GROWING',
  BLINKING: 'BLINKING',  // 闪烁
  FADE_IN_OUT: 'FADE_IN_OUT',  // 淡入淡出
  ROTATING: 'ROTATING',  // 旋转
  SCALE: 'SCALE', //
};


export const ANIMATE_TYPES_DISPLAY = {
  [ANIMATE_TYPES.NUMBER_GROWING]: '增长',
  [ANIMATE_TYPES.SCALE]: '缩放',
  [ANIMATE_TYPES.BLINKING]: '闪烁',
  [ANIMATE_TYPES.FADE_IN_OUT]: '淡入淡出',
  [ANIMATE_TYPES.ROTATING]: '旋转',
}
