
export const ANIMATE_TYPE_MARQUEE_IMAGE_VIDEO = {
  GO_LEFT: 'GO_LEFT',
  GO_RIGHT: 'GO_RIGHT',
  RANDOM: 'RANDOM',
  STILL: 'STILL',
}

export const ANIMATE_TYPE_MARQUEE_IMAGE_VIDEO_DISPLAY = {
  [ANIMATE_TYPE_MARQUEE_IMAGE_VIDEO.GO_LEFT]: '从右往左移动',
  [ANIMATE_TYPE_MARQUEE_IMAGE_VIDEO.GO_RIGHT]: '从左往右移动',
  [ANIMATE_TYPE_MARQUEE_IMAGE_VIDEO.RANDOM]: '随机乱动',
  [ANIMATE_TYPE_MARQUEE_IMAGE_VIDEO.STILL]: '保持不动',
}
