export const SUB_TYPE = {
  TEXT: 'text',
  IMAGE: 'image',
  PIE_CHART: 'pie_chart',
  BAR_CHART: 'bar_chart',
  LINE_CHART: 'line_chart',
  GAUGE_CHART: 'gauge_chart',
  STACKING_CHART: 'stacking_chart',
  SPARKLINE_CHART: 'sparkline_chart',
  ECHART_CHART: 'echart_chart',
  SPRITE: 'sprite',
  SPRITE_B: 'sprite_B',
  TIME: 'time',
  VIDEO: 'video',
  MARQUEE: 'Marquee',
  TABLE: 'TABLE',
  TABLE_ONE_ROW_ANIMATE: 'TABLE_ONE_ROW_ANIMATE',
  SWIPER: 'SWIPER',
  SWIPER_JS: 'SWIPER_JS',
  SWIPER_ONE_PICTURE: 'SWIPER_ONE_PICTURE',
  SWIPER_IMAGE_TEXT: 'SWIPER_IMAGE_TEXT',
  ROLL_ONE_LINE: 'ROLL_ONE_LINE',
  BUTTON_ACTIVE_ONE: 'BUTTON_ACTIVE_ONE',
}

export const SUB_TYPE_DISPLAY = {
  [SUB_TYPE.TEXT]: '文字',
  [SUB_TYPE.IMAGE]: '图片',
  [SUB_TYPE.PIE_CHART]: '饼图',
  [SUB_TYPE.BAR_CHART]: '柱状图',
  [SUB_TYPE.LINE_CHART]: '曲线图',
  [SUB_TYPE.GAUGE_CHART]: '环形图',
  [SUB_TYPE.STACKING_CHART]: '柱堆图',
  [SUB_TYPE.SPARKLINE_CHART]: '折线图',
  [SUB_TYPE.ECHART_CHART]: '一茶特',
  [SUB_TYPE.SPRITE]: '雪碧图',
  [SUB_TYPE.TIME]: '时间',
  [SUB_TYPE.SPRITE_B]: '复杂雪碧图',
  [SUB_TYPE.VIDEO]: '视频',
  [SUB_TYPE.MARQUEE]: '跑马灯',
  [SUB_TYPE.TABLE]: '表格',
  [SUB_TYPE.TABLE_ONE_ROW_ANIMATE]: '表格单行滚动',
  [SUB_TYPE.SWIPER]: '轮播图',
  [SUB_TYPE.SWIPER_JS]: '轮播图评论',
  [SUB_TYPE.SWIPER_ONE_PICTURE]: '轮播图单大图',
  [SUB_TYPE.SWIPER_IMAGE_TEXT]: '轮播图文',
  [SUB_TYPE.ROLL_ONE_LINE]: '单行文字动画',
  [SUB_TYPE.BUTTON_ACTIVE_ONE]: '激活互斥按钮',
}
