import { SUB_TYPE } from "./subType";

export const SUB_TYPE_DISPLAY = {
  [SUB_TYPE.TEXT]: '文字',
  [SUB_TYPE.IMAGE]: '图片',
  [SUB_TYPE.PIE_CHART]: '饼图',
  [SUB_TYPE.BAR_CHART]: '柱状图',
  [SUB_TYPE.LINE_CHART]: '曲线图',
  [SUB_TYPE.GAUGE_CHART]: '环形图',
  [SUB_TYPE.STACKING_CHART]: '柱堆图',
  [SUB_TYPE.SPARKLINE_CHART]: '折线图',
  [SUB_TYPE.ECHART_CHART]: '一茶特',
  [SUB_TYPE.SPRITE]: '雪碧图',
  [SUB_TYPE.TIME]: '时间',
  [SUB_TYPE.SPRITE_B]: '复杂雪碧图',
  [SUB_TYPE.VIDEO]: '视频',
  [SUB_TYPE.MARQUEE]: '跑马灯',
  [SUB_TYPE.TABLE]: '表格',
  [SUB_TYPE.TABLE_ONE_ROW_ANIMATE]: '表格单行滚动',
  [SUB_TYPE.SWIPER]: '轮播图',
  [SUB_TYPE.SWIPER_JS]: '轮播图评论',
  [SUB_TYPE.SWIPER_ONE_PICTURE]: '轮播图单大图',
  [SUB_TYPE.SWIPER_IMAGE_TEXT]: '轮播图文',
  [SUB_TYPE.ROLL_ONE_LINE]: '单行文字动画',
  [SUB_TYPE.BUTTON_ACTIVE_ONE]: '激活互斥按钮',
  [SUB_TYPE.THREE_CANVAS]: '模型画布',
  [SUB_TYPE.MARQUEE_IMAGE_VIDEO]: '跑马灯图片视频',
  [SUB_TYPE.SLOW_UP_TEXT]: '缓慢上升文字',
  [SUB_TYPE.SLOW_UP_TEXT_TWO_COLUMN]: '缓慢上升文字两列',
  [SUB_TYPE.FABRIC_CANVAS]: 'Fabric 画布',
  [SUB_TYPE.CHARTJS]: 'CHART JS',
  [SUB_TYPE.TABLE_BIND_DATA]: '数据绑定的表',
  [SUB_TYPE.SWIPER_VIDEO]: '轮播视频',
  [SUB_TYPE.ONE_LINE_RIGHT_TO_LEFT]: '单行文字从右到左',
  [SUB_TYPE.ONE_LINE_RIGHT_TO_LEFT_MULTIPLE]: '单行多文从右到左',
  [SUB_TYPE.RECTANGLE]: '矩形',
  [SUB_TYPE.E_CHART_BAR]: 'ECharts条形图',
  [SUB_TYPE.E_CHART_RING]: 'ECharts环形图',
  [SUB_TYPE.E_CHART_RING_2]: 'ECharts环形图间隙',
  [SUB_TYPE.E_CHART_PIE]: 'ECharts简单饼',
  [SUB_TYPE.E_CHART_STACKED_AREA]: 'ECharts堆叠面积',
  [SUB_TYPE.E_CHART_STACKED_LINE]: 'ECharts堆叠线',
  [SUB_TYPE.E_CHART_LINE]: 'ECharts折线',
  [SUB_TYPE.E_CHART_STACK_BAR_V]: 'ECharts堆叠柱v',
  [SUB_TYPE.E_CHART_STACK_BAR_H]: 'ECharts堆叠柱h',
  [SUB_TYPE.E_CHART_RADAR]: 'ECharts雷达',
  [SUB_TYPE.E_CHART_GAUGE]: 'ECharts仪表盘',
  [SUB_TYPE.E_CHART_GAUGE_TEMPERATURE]: 'ECharts仪表温度',
  [SUB_TYPE.E_CHART_GAUGE_SPEED]: 'ECharts仪表速度',
  [SUB_TYPE.IFRAME]: 'iframe',
}

